# Generated by Django 4.0.2 on 2022-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=128)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.BooleanField(default=False)),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('goal', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('wrist', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
    ]
