# Generated by Django 4.0.2 on 2022-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='caloricity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='caloricity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
