# Generated by Django 4.0.2 on 2022-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0002_alter_user_options_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('caloricity', models.PositiveSmallIntegerField()),
                ('proteins', models.PositiveSmallIntegerField()),
                ('fats', models.PositiveSmallIntegerField()),
                ('carbohydrates', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='activity_norm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consumption_norm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='somatotype',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
