# Generated by Django 4.0.2 on 2022-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0002_alter_activity_caloricity_alter_food_caloricity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
