# Generated by Django 4.0.2 on 2022-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0003_alter_user_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BMI',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activity_norm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='consumption_norm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='somatotype',
        ),
    ]
