# Generated by Django 4.0.2 on 2022-04-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0003_food_user_activity_norm_user_consumption_norm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=80)),
                ('caloricity', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
        migrations.CreateModel(
            name='Starvation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('stopped_at', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hls.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('amount', models.PositiveSmallIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hls.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hls.user')),
            ],
        ),
    ]
