# Generated by Django 4.0.2 on 2022-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls', '0004_remove_user_bmi_remove_user_activity_norm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starvation',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
